### ISSUE TITLE
Increase productivity with non-stop index

### ISSUE THREAD

**Issue by GregOnNet** [philiptober/rapid-git#10]
I wonder if it is a good idea to merge both indexes from `untracked` and `tracked` files into one single index.

![image](https://cloud.githubusercontent.com/assets/444278/13928875/d0fbe570-ef97-11e5-99ce-664b3053c16e.png)

In that way we are able to use one command to `track` and `stage` files.

What do you think?

**Comment by philiptober** [comment]
I never thought about this possibility, but I do not mind trying it for some time. Maybe tracking and staging files will go a bit smoother this way. 

**There a few things we may want to think about beforehand:**
- If we merge `rapid track` and `rapid stage`, then the impact of the indexes `..`, `#..` and `..#` will obviously increase, as they target both, untracked and unstaged files. Also, currently we can select all untracked files by simply using `..`. Afterwards we have to use `#..#` instead. So depending on the point of view, you could say, that we loose a tiny bit of comfortability here.
- Do we also want to merge `rapid drop` and `rapid remove`? Doing that would mean, that the user could accidentally delete files of the untracked files area, because of a simple fuck up, when he tried to only drop some modifications.
- Do we allow `rapid diff` to use indexes of untracked files too

What we have to do to achieve the change:
- change the filter variable we pass to `__rapid_index_command` when calling `__rapid__track`, `__rapid__stage`, `__rapid__drop`, `__rapid__remove` and maybe even `__rapid__diff``
- optionally merge the commands `__rapid__track` and `__rapid__stage` into one command
- optionally merge the commands `__rapid__drop` and `__rapid__remove` into one command
- revise `__rapid_status_of_type`

Looking at the sample image above, I got al little curious. Did you already implement the whole change locally?

**Comment by GregOnNet** [comment]
Well thinking about this topic I am not sure if we should implement this feature.

Users of rapid-git are familiar with git. They know the concept of indexed and not indexed files. 
When we "sugar" the whoule staging process with one single command it might confuse every one.
We simply would not be in sync with git's API.
Further more it's a high effort to achieve this.

Maybe it's not worth to realize this idea.

**Comment by philiptober** [comment]
Then let's close this issue for now. We can think about doing this at a later date again, if we feel like it.

**Comment by GregOnNet** [comment]
:+1:
